# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '19.0.1'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudConnection'
    organization: 'mtu-jodo'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'mtu-jodo'
    #cliProjectKey: 'MTU-Jodo_Jōdō'
    cliProjectName: 'Jōdō'
    cliProjectVersion: '1.0'
    cliSources: '.'
- task: SonarCloudAnalyze@1


- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
